import type { Category, Complaint, DraftExercise, Exercise, PoseId } from "./types";

export const CATEGORIES: Category[] = [
  { id: "cat-body", name: "Körper", slug: "koerper", parentId: null, description: "Bewegung, Kraft, Haltung.", isSystem: true },
  { id: "cat-mind", name: "Geist", slug: "geist", parentId: null, description: "Mantras, Meditation, Aufmerksamkeit.", isSystem: true },
  { id: "cat-daily", name: "Alltag", slug: "alltag", parentId: null, description: "Kurze Rituale für Morgen, Pause und Abend.", isSystem: true },
  { id: "cat-mobility", name: "Beweglichkeit", slug: "beweglichkeit", parentId: "cat-body", description: "Sanftes Öffnen und Fließen.", isSystem: true },
  { id: "cat-strength", name: "Kraft", slug: "kraft", parentId: "cat-body", description: "Stabile, einfache Kraftreize.", isSystem: true },
  { id: "cat-posture", name: "Haltung", slug: "haltung", parentId: "cat-body", description: "Aufrichten ohne Verkrampfen.", isSystem: true },
  { id: "cat-breath", name: "Atmung", slug: "atmung", parentId: "cat-body", description: "Atem als Übung, nicht nur Beiwerk.", isSystem: true },
  { id: "cat-neck", name: "Nacken", slug: "nacken", parentId: "cat-body", description: "Nacken und Halswirbelsäule.", isSystem: true },
  { id: "cat-shoulders", name: "Schultern", slug: "schultern", parentId: "cat-body", description: "Schultergürtel und Brustkorb.", isSystem: true },
  { id: "cat-back", name: "Rücken", slug: "ruecken", parentId: "cat-body", description: "Lenden- und Brustwirbelsäule.", isSystem: true },
  { id: "cat-hips", name: "Hüfte", slug: "huefte", parentId: "cat-body", description: "Becken, Hüftbeuger, Gesäß.", isSystem: true },
  { id: "cat-knees", name: "Knie", slug: "knie", parentId: "cat-body", description: "Kniegelenke und Beinachsen.", isSystem: true },
  { id: "cat-mantras", name: "Mantras", slug: "mantras", parentId: "cat-mind", description: "Sätze, die du regelmäßig sagst oder denkst.", isSystem: true },
  { id: "cat-meditation", name: "Meditation", slug: "meditation", parentId: "cat-mind", description: "Stille, Scan, Sitzen.", isSystem: true },
  { id: "cat-mindfulness", name: "Achtsamkeit", slug: "achtsamkeit", parentId: "cat-mind", description: "Kurze Anker im Alltag.", isSystem: true },
  { id: "cat-morning", name: "Morgen", slug: "morgen", parentId: "cat-daily", description: "Sanfter Start.", isSystem: true },
  { id: "cat-pause", name: "Pause", slug: "pause", parentId: "cat-daily", description: "Zwischendurch, oft am Schreibtisch.", isSystem: true },
  { id: "cat-evening", name: "Abend", slug: "abend", parentId: "cat-daily", description: "Runterkommen vor dem Schlaf.", isSystem: true },
];

export const COMPLAINTS: Complaint[] = [
  { id: "comp-neck", name: "Nackensteifheit", summary: "Verspannter Nacken, Kopf fühlt sich schwer an.", hint: "Kleine Bewegungen, oft, statt einmal hart zu dehnen." },
  { id: "comp-shoulders", name: "Hängende Schultern", summary: "Schultern nach vorn, Brustkorb eng.", hint: "Öffnen und absenken, nicht nur nach hinten ziehen." },
  { id: "comp-back", name: "Rückenschmerzen", summary: "Untere oder mittlere Wirbelsäule protestiert.", hint: "Wechsel aus Beugen und Strecken, nie in den Schmerz hinein." },
  { id: "comp-hips", name: "Enge Hüfte", summary: "Langes Sitzen, Hüftbeuger kurz.", hint: "Täglich kurz öffnen wirkt oft besser als selten lang." },
  { id: "comp-knees", name: "Knieunruhe", summary: "Knie fühlen sich unbequem oder instabil an.", hint: "Kraft um das Gelenk, kein übertriebenes Dehnen." },
  { id: "comp-stress", name: "Stress & Unruhe", summary: "Gedanken rasen, Körper ist an.", hint: "Atem und Mantra zuerst, Bewegung nur so viel, wie der Tag noch trägt." },
  { id: "comp-sleep", name: "Schwer einschlafen", summary: "Der Tag geht im Kopf weiter.", hint: "Atem und Mantra vor dem Liegen, kein Training spätabends." },
  { id: "comp-focus", name: "Zerstreutheit", summary: "Du fängst vieles an und verlierst den Faden.", hint: "Kurze Anker, die du wirklich schaffst." },
];

function steps(
  items: Array<[PoseId, string, number?]>,
): DraftExercise["steps"] {
  return items.map(([pose, text, durationSec]) => ({
    pose,
    text,
    durationSec: durationSec ?? 8,
  }));
}

function nowIso() {
  return "2026-01-01T09:00:00.000Z";
}

function exercise(
  partial: Omit<DraftExercise, "isSystem" | "source"> & { id: string },
): Exercise {
  const createdAt = nowIso();
  const { id, ...rest } = partial;
  return {
    ...rest,
    id,
    isSystem: true,
    source: { type: "catalog" },
    createdAt,
    updatedAt: createdAt,
  };
}

export const CATALOG_EXERCISES: Exercise[] = [
  exercise({
    id: "ex-neck-circles",
    title: "Nacken langsam kreisen",
    summary: "Kleine Kreise, die den Nacken erinnern, dass er sich bewegen darf.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-neck", "cat-mobility", "cat-pause"],
    complaintIds: ["comp-neck", "comp-shoulders"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Jeden Tag 1–2 Minuten, besonders nach Bildschirmarbeit. Das darf dauerhaft im Plan bleiben.",
    },
    steps: steps([
      ["stand", "Stell dich oder setz dich aufrecht hin. Schultern schwer, Kiefer locker."],
      ["neckTilt", "Neige das Ohr zur Schulter. Nicht ziehen, nur nachgeben.", 10],
      ["neckTilt", "Kleine Kreise, halb so groß wie du denkst. Atme dabei ruhig.", 20],
      ["stand", "Komm zur Mitte zurück. Spüre, ob der Kopf leichter sitzt."],
    ]),
  }),
  exercise({
    id: "ex-shoulder-rolls",
    title: "Schulterkreisen",
    summary: "Die Schultern nach hinten-unten schicken, statt sie am Ohr zu parken.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-shoulders", "cat-posture", "cat-pause"],
    complaintIds: ["comp-shoulders", "comp-neck"],
    defaultDurationSec: 80,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Unter der Woche mehrmals kurz, nicht einmal lang.",
    },
    steps: steps([
      ["stand", "Arme hängen lassen. Spüre das Gewicht der Hände."],
      ["chestOpen", "Schultern nach vorn, hoch, hinten, unten – große, langsame Kreise.", 16],
      ["reachUp", "Einmal einatmen, Arme heben, ausatmen, Schultern fallen lassen."],
      ["stand", "Prüfe: Sind die Schultern näher an den Hüften als am Kiefer?"],
    ]),
  }),
  exercise({
    id: "ex-cat-cow",
    title: "Katze und Kuh",
    summary: "Die Wirbelsäule wellen, statt sie starr zu halten.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-back", "cat-mobility", "cat-morning"],
    complaintIds: ["comp-back", "comp-hips"],
    defaultDurationSec: 120,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 6,
      note: "Sechs Wochen täglich, danach mindestens an Bürotagen behalten.",
    },
    steps: steps([
      ["cat", "Vierfüßler: Hände unter Schultern, Knie unter Hüften. Rund den Rücken, Blick zum Bauch.", 10],
      ["cow", "Mit der Einatmung Brustbein nach vorn, Steißbein nach oben, Blick leicht heben.", 10],
      ["cat", "Mit der Ausatmung wieder runden. Bewege dich im Atem, nicht gegen ihn.", 16],
      ["child", "Setz dich zu den Fersen, wenn du fertig bist, und ruhe kurz."],
    ]),
  }),
  exercise({
    id: "ex-cobra",
    title: "Sanfte Cobra",
    summary: "Eine kleine Rückbeuge, die den oberen Rücken weckt.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-back", "cat-posture", "cat-mobility"],
    complaintIds: ["comp-back", "comp-shoulders"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "days",
      daysOfWeek: [1, 3, 5, 0],
      timesPerWeek: 4,
      recommendedWeeks: 8,
      note: "Vier Mal pro Woche. Am Abend weicher halten als am Morgen.",
    },
    steps: steps([
      ["lie", "Bauchlage, Stirn kurz abgelegt, Hände neben der Brust."],
      ["cobra", "Zieh die Brust nach vorn-oben. Die Unterarme dürfen bleiben. Nacken lang.", 16],
      ["lie", "Senke dich ab und spüre die Länge der Vorderseite."],
    ]),
  }),
  exercise({
    id: "ex-child",
    title: "Kindeshaltung",
    summary: "Eine Pause in Form einer Haltung.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-back", "cat-evening", "cat-mobility"],
    complaintIds: ["comp-back", "comp-stress"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Immer dann, wenn der Tag zu voll wurde. Auch 45 Sekunden zählen.",
    },
    steps: steps([
      ["sit", "Knie weit oder eng, wie es für deine Hüfte freundlich ist."],
      ["child", "Gesäß zu den Fersen, Arme nach vorn oder neben dem Körper. Atme in den Rücken.", 30],
      ["sit", "Rolle dich langsam auf, Kopf zuletzt."],
    ]),
  }),
  exercise({
    id: "ex-forward-fold",
    title: "Stehende Vorbeuge",
    summary: "Der Oberkörper darf schwer werden, die Beine tragen.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-mobility", "cat-back", "cat-morning"],
    complaintIds: ["comp-back", "comp-stress"],
    defaultDurationSec: 70,
    suggestedRhythm: {
      kind: "weekdays",
      recommendedWeeks: 4,
      note: "Unter der Woche nach dem Aufstehen. Knie dürfen weich bleiben.",
    },
    steps: steps([
      ["stand", "Füße hüftbreit. Einatmen, Länge im Rücken."],
      ["fold", "Ausatmen, Oberkörper hängen lassen. Kopf schwer, Knie gebeugt ist richtig.", 20],
      ["reachUp", "Mit leichtem Schwung wieder aufrichten, Arme mitnehmen."],
      ["stand", "Stehen bleiben und nachspüren."],
    ]),
  }),
  exercise({
    id: "ex-squat",
    title: "Langsame Kniebeuge",
    summary: "Kraft für Beine und eine klarere Beinachse.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-strength", "cat-knees"],
    complaintIds: ["comp-knees", "comp-hips"],
    defaultDurationSec: 100,
    defaultReps: 8,
    suggestedRhythm: {
      kind: "days",
      daysOfWeek: [1, 3, 5],
      timesPerWeek: 3,
      recommendedWeeks: 8,
      note: "Drei Mal pro Woche. Qualität vor Tiefe.",
    },
    steps: steps([
      ["stand", "Füße etwas breiter als die Hüfte, Fußspitzen leicht außen."],
      ["squat", "Senke dich ab, als würdest du dich auf einen Stuhl setzen. Knie zeigen über die Füße.", 12],
      ["stand", "Drück dich über die ganze Fußsohle wieder hoch. 8 ruhige Wiederholungen."],
    ]),
  }),
  exercise({
    id: "ex-lunge",
    title: "Ausfallschritt zum Hüftbeuger",
    summary: "Das Gegenmittel zum Sitzen: vordere Hüfte lang.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-hips", "cat-mobility", "cat-pause"],
    complaintIds: ["comp-hips", "comp-back"],
    defaultDurationSec: 120,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 4,
      note: "Vier Wochen täglich je Seite, danach an Sitz-Tagen behalten.",
    },
    steps: steps([
      ["stand", "Großer Schritt nach hinten mit dem rechten Fuß."],
      ["lunge", "Hintere Ferse hebt, vordere Hüfte sinkt. Schambein leicht nach vorn-oben.", 20],
      ["stand", "Seite wechseln und gleich lang bleiben."],
    ]),
  }),
  exercise({
    id: "ex-hip-open",
    title: "Sitzender Hüftöffner",
    summary: "Eine Seite der Hüfte nach der anderen weich machen.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-hips", "cat-evening", "cat-mobility"],
    complaintIds: ["comp-hips", "comp-back"],
    defaultDurationSec: 150,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 6,
      note: "Abends 2 Minuten. Sechs Wochen sind ein guter erster Block.",
    },
    steps: steps([
      ["sit", "Aufrecht sitzen, ein Fuß vor dem anderen oder Fußgelenk auf dem Oberschenkel, wenn das Knie einverstanden ist."],
      ["hipOpen", "Kipp das Becken leicht nach vorn. Atme in die Leiste.", 30],
      ["sit", "Wechsel die Seite. Nicht ziehen, nur bleiben."],
    ]),
  }),
  exercise({
    id: "ex-plank",
    title: "Stütze auf den Unterarmen",
    summary: "Mitte anschalten, ohne den Atem anzuhalten.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-strength", "cat-posture"],
    complaintIds: ["comp-back"],
    defaultDurationSec: 40,
    suggestedRhythm: {
      kind: "days",
      daysOfWeek: [2, 4, 6],
      timesPerWeek: 3,
      recommendedWeeks: 8,
      note: "Drei Mal pro Woche, 20–40 Sekunden. Länger nur, wenn die Form bleibt.",
    },
    steps: steps([
      ["plank", "Unterarme parallel, Becken weder durchhängen noch spitz nach oben. Schau auf den Boden.", 20],
      ["child", "Knie ab, kurz in die Kindeshaltung und nachspüren."],
    ]),
  }),
  exercise({
    id: "ex-tree",
    title: "Baum",
    summary: "Eine Minute Balance, die den Tag sammelt.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-strength", "cat-mindfulness", "cat-morning"],
    complaintIds: ["comp-focus", "comp-knees"],
    defaultDurationSec: 80,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Morgens je Seite 20–30 Sekunden. Immer erlaubt, die Zehen am Boden zu lassen.",
    },
    steps: steps([
      ["stand", "Finde einen Punkt zum Anschauen. Gewicht auf den linken Fuß."],
      ["tree", "Rechte Fußsohle an Waden oder Oberschenkel, nie gegen das Knie. Hände vor der Brust oder nach oben.", 20],
      ["stand", "Seite wechseln. Wenn du fällst, bist du mittendrin, nicht draußen."],
    ]),
  }),
  exercise({
    id: "ex-warrior",
    title: "Kriegerlicht",
    summary: "Standfestigkeit mit Länge in den Armen.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-strength", "cat-hips", "cat-morning"],
    complaintIds: ["comp-hips", "comp-focus"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "days",
      daysOfWeek: [1, 3, 5],
      timesPerWeek: 3,
      recommendedWeeks: 4,
      note: "Drei Mal pro Woche als Mini-Kraft und Fokus.",
    },
    steps: steps([
      ["stand", "Weiter Ausfallschritt, hintere Ferse verankert, soweit es geht."],
      ["warrior", "Vorderes Knie über dem Fuß, Arme hoch oder zur Seite. Atme in die Breite der Brust.", 20],
      ["stand", "Aufrichten und die andere Seite."],
    ]),
  }),
  exercise({
    id: "ex-chest-open",
    title: "Brustöffner an der Tür",
    summary: "Den vorderen Schultergürtel erinnern, dass er länger sein darf.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-shoulders", "cat-posture", "cat-pause"],
    complaintIds: ["comp-shoulders", "comp-neck"],
    defaultDurationSec: 70,
    suggestedRhythm: {
      kind: "weekdays",
      recommendedWeeks: null,
      note: "An Bürotagen, nach längeren Calls. Dauerhaft sinnvoll.",
    },
    steps: steps([
      ["stand", "Stell dich in einen Türrahmen oder verschränke die Hände hinter dem Rücken."],
      ["chestOpen", "Brustbein hebt sich, Schulterblätter gleiten zur Gesäßtasche. Nacken bleibt lang.", 20],
      ["stand", "Lass los und schüttle die Arme aus."],
    ]),
  }),
  exercise({
    id: "ex-twist",
    title: "Sitzende Drehung",
    summary: "Eine ruhige Rotation für die Brustwirbelsäule.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-back", "cat-mobility", "cat-pause"],
    complaintIds: ["comp-back"],
    defaultDurationSec: 80,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 4,
      note: "Täglich je Seite ein Atemfenster von 20 Sekunden.",
    },
    steps: steps([
      ["sit", "Sitzbeinhöcker geerdet, Wirbelsäule lang."],
      ["twist", "Drehe dich aus der Taille, nicht aus dem Kiefer. Blick folgt zuletzt.", 16],
      ["sit", "Mitte, andere Seite, gleiche Dauer."],
    ]),
  }),
  exercise({
    id: "ex-box-breath",
    title: "Boxatmung",
    summary: "Vier Seiten, ein klarer Rhythmus.",
    kind: "breath",
    categoryIds: ["cat-body", "cat-breath", "cat-mind", "cat-pause"],
    complaintIds: ["comp-stress", "comp-focus"],
    defaultDurationSec: 120,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Immer, wenn Unruhe kommt – und einmal geplant am Tag, damit du es nicht vergisst.",
    },
    steps: steps([
      ["sit", "Sitz oder Stand. Schultern schwer."],
      ["breathe", "4 Sekunden ein, 4 halten, 4 aus, 4 halten. Vier bis sechs Runden.", 32],
      ["sit", "Wieder normal atmen. Nichts muss sich großartig anfühlen."],
    ]),
  }),
  exercise({
    id: "ex-478",
    title: "4-7-8 Atmung",
    summary: "Ein längeres Ausatmen, das das Nervensystem bremst.",
    kind: "breath",
    categoryIds: ["cat-body", "cat-breath", "cat-evening"],
    complaintIds: ["comp-sleep", "comp-stress"],
    defaultDurationSec: 100,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Abends im Bett oder davor. Dauerhaft im Plan lassen.",
    },
    steps: steps([
      ["lie", "Liegen oder sitzen. Zungenspitze darf hinter den Schneidezähnen ruhen."],
      ["breathe", "Einatmen 4, halten 7, ausatmen 8. Vier Runden reichen.", 40],
      ["lie", "Danach nichts weiter tun. Einfach liegen bleiben."],
    ]),
  }),
  exercise({
    id: "ex-coherent",
    title: "Kohärentes Atmen",
    summary: "Etwa sechs Atemzüge pro Minute, ohne Technik-Theater.",
    kind: "breath",
    categoryIds: ["cat-body", "cat-breath", "cat-mindfulness"],
    complaintIds: ["comp-stress", "comp-focus"],
    defaultDurationSec: 180,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 8,
      note: "Drei Minuten täglich für acht Wochen, danach nach Bedarf.",
    },
    steps: steps([
      ["sit", "Bequem sitzen. Eine Hand am Bauch, wenn es hilft."],
      ["breathe", "5 Sekunden ein, 5 Sekunden aus. Weich, durch die Nase, wenn möglich.", 40],
      ["sit", "Öffne die Augen, wenn sie zu waren, und nimm den Raum wieder wahr."],
    ]),
  }),
  exercise({
    id: "ex-mantra-here",
    title: "Mantra: Ich bin hier",
    summary: "Ein Satz, der dich aus dem Vorher und Nachher holt.",
    kind: "mantra",
    categoryIds: ["cat-mind", "cat-mantras", "cat-mindfulness", "cat-pause"],
    complaintIds: ["comp-focus", "comp-stress"],
    defaultDurationSec: 60,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Morgens einmal bewusst, und jederzeit, wenn du merkst, dass du nur noch im Kopf bist.",
    },
    steps: steps([
      ["heart", "Hand aufs Brustbein. Einatmen."],
      ["heart", "Leise oder innerlich: „Ich bin hier.“ Ausatmen: „Genau jetzt.“", 20],
      ["stand", "Augen auf. Einen Gegenstand im Raum benennen."],
    ]),
  }),
  exercise({
    id: "ex-mantra-fit",
    title: "Mantra: I am fit",
    summary: "Nicht als Behauptung über den Körper, sondern als Richtung.",
    kind: "mantra",
    categoryIds: ["cat-mind", "cat-mantras", "cat-morning"],
    complaintIds: ["comp-focus"],
    defaultDurationSec: 75,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Täglich am Morgen, bevor das Handy die Stimmung setzt.",
    },
    steps: steps([
      ["stand", "Zwei Fußsohlen auf dem Boden. Aufrecht, nicht militärisch."],
      ["heart", "Sag langsam: „I am fit.“ Fit im Sinn von: ich bleibe in Verbindung mit dem, was mir guttut.", 24],
      ["reachUp", "Einmal strecken, als würdest du den Satz in den Tag heben."],
      ["stand", "Fertig. Kein Extra-Beweis nötig."],
    ]),
  }),
  exercise({
    id: "ex-gratitude",
    title: "Drei Dankbarkeiten",
    summary: "Drei konkrete Dinge, nicht drei Slogans.",
    kind: "mind",
    categoryIds: ["cat-mind", "cat-mindfulness", "cat-evening"],
    complaintIds: ["comp-sleep", "comp-stress"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Abends. Immer. Es ist kurz genug, dass Vergessen die einzige Hürde ist.",
    },
    steps: steps([
      ["sit", "Setz dich oder lieg. Kein Journal nötig, Stimme reicht."],
      ["heart", "Nenne drei Dinge von heute. So konkret wie „das warme Wasser“ statt „mein Leben“.", 30],
      ["sit", "Einen Atemzug länger bleiben als du willst, dann aufhören."],
    ]),
  }),
  exercise({
    id: "ex-body-scan",
    title: "Mini-Bodyscan",
    summary: "Vom Fuß bis zum Kiefer, ohne etwas zu reparieren.",
    kind: "mind",
    categoryIds: ["cat-mind", "cat-meditation", "cat-evening"],
    complaintIds: ["comp-sleep", "comp-stress"],
    defaultDurationSec: 180,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 4,
      note: "Vier Wochen abends. Danach mindestens an unruhigen Tagen.",
    },
    steps: steps([
      ["lie", "Liegen, Arme neben dem Körper, Füße fallen lassen."],
      ["breathe", "Wandere mit der Aufmerksamkeit: Füße, Knie, Becken, Rücken, Schultern, Kiefer.", 40],
      ["lie", "Wenn Gedanken kommen, zurück zum nächsten Körperteil. Fertig ist, wenn du bei den Augenlidern bist."],
    ]),
  }),
  exercise({
    id: "ex-54321",
    title: "5-4-3-2-1 Anker",
    summary: "Fünf Dinge sehen, vier berühren, drei hören, zwei riechen, eins schmecken.",
    kind: "mind",
    categoryIds: ["cat-mind", "cat-mindfulness", "cat-pause"],
    complaintIds: ["comp-stress", "comp-focus"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "every_n_days",
      everyNDays: 1,
      recommendedWeeks: null,
      note: "Nicht starr planen: aufheben für Momente, in denen es kippt – und einmal pro Woche üben, damit der Weg bekannt ist.",
    },
    steps: steps([
      ["stand", "Bleib, wo du bist. Kein Extra-Ort."],
      ["heart", "5 Dinge, die du siehst. 4, die du fühlst. 3 Geräusche. 2 Gerüche. 1 Geschmack.", 30],
      ["stand", "Ein normaler Atemzug. Weiter mit dem, was als Nächstes da ist."],
    ]),
  }),
  exercise({
    id: "ex-morning-reach",
    title: "Morgenstrecken im Stand",
    summary: "Drei Atemzüge Länge, bevor der Tag dich übernimmt.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-morning", "cat-mobility", "cat-daily"],
    complaintIds: ["comp-back", "comp-shoulders"],
    defaultDurationSec: 60,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Jeden Morgen, noch bevor Mails. Immer behalten.",
    },
    steps: steps([
      ["stand", "Noch im Schlafanzug ist erlaubt."],
      ["reachUp", "Arme heben, seitlich lang werden, in die Fersen sinken.", 16],
      ["fold", "Einmal schwer hängen lassen.", 8],
      ["stand", "Aufrichten. Tag darf beginnen."],
    ]),
  }),
  exercise({
    id: "ex-desk-break",
    title: "Zwei-Minuten-Bildschirmpause",
    summary: "Nacken, Schultern, Atem – das, was du zwischen zwei Tasks vergisst.",
    kind: "movement",
    categoryIds: ["cat-daily", "cat-pause", "cat-neck", "cat-shoulders"],
    complaintIds: ["comp-neck", "comp-shoulders", "comp-focus"],
    defaultDurationSec: 120,
    suggestedRhythm: {
      kind: "weekdays",
      recommendedWeeks: null,
      note: "An Arbeitstagen, idealerweise zweimal. Der Plan erinnert dich an eine Runde; die zweite ist Bonus.",
    },
    steps: steps([
      ["stand", "Steh auf. Ja, wirklich aufstehen."],
      ["neckTilt", "Nacken neigen, beide Seiten.", 12],
      ["chestOpen", "Schultern kreisen und die Brust öffnen.", 10],
      ["breathe", "Vier ruhige Atemzüge.", 16],
    ]),
  }),
  exercise({
    id: "ex-jaw-release",
    title: "Kiefer locker lassen",
    summary: "Zunge, Zähne und Schläfen erinnern, dass sie nicht arbeiten müssen.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-neck", "cat-pause", "cat-daily"],
    complaintIds: ["comp-neck", "comp-stress"],
    defaultDurationSec: 70,
    suggestedRhythm: {
      kind: "weekdays",
      recommendedWeeks: null,
      note: "An Arbeitstagen, sobald du merkst, dass die Zähne aufeinanderliegen.",
    },
    steps: steps([
      ["sit", "Lippen geschlossen, Zähne nicht. Zunge hinter den Schneidezähnen ablegen."],
      ["neckTilt", "Kiefer ganz leicht nach links und rechts gleiten lassen. Kein Dehnen, nur Loslassen.", 16],
      ["sit", "Ein Atemzug in die Schläfen. Schultern dürfen mitfallen."],
    ]),
  }),
  exercise({
    id: "ex-wrist-circles",
    title: "Handgelenke kreisen",
    summary: "Zwei Kreise gegen das starre Tippen.",
    kind: "movement",
    categoryIds: ["cat-daily", "cat-pause", "cat-mobility"],
    complaintIds: ["comp-shoulders", "comp-focus"],
    defaultDurationSec: 60,
    suggestedRhythm: {
      kind: "weekdays",
      recommendedWeeks: null,
      note: "Unter der Woche zwischen zwei Schreibblöcken. Kurz genug, um es wirklich zu tun.",
    },
    steps: steps([
      ["stand", "Arme vor dem Körper, Finger locker."],
      ["chestOpen", "Handgelenke langsam kreisen, dann die andere Richtung. Atme dabei normal.", 20],
      ["stand", "Hände ausschütteln, als wären sie nass."],
    ]),
  }),
  exercise({
    id: "ex-eye-rest",
    title: "Blick in die Ferne",
    summary: "Zwanzig Sekunden weit schauen, damit die Augen nicht nur den Bildschirm kennen.",
    kind: "mind",
    categoryIds: ["cat-daily", "cat-pause", "cat-mindfulness"],
    complaintIds: ["comp-focus", "comp-stress"],
    defaultDurationSec: 50,
    suggestedRhythm: {
      kind: "weekdays",
      recommendedWeeks: null,
      note: "An Bildschirmtagen oft. Der Plan erinnert an eine Runde; weitere sind freiwillig.",
    },
    steps: steps([
      ["sit", "Vom Schirm wegdrehen. Schultern schwer."],
      ["breathe", "Einen Punkt in der Ferne wählen und 20 ruhige Sekunden dort bleiben.", 20],
      ["sit", "Blinzeln. Danach darf der Bildschirm wieder da sein."],
    ]),
  }),
  exercise({
    id: "ex-pelvic-tilt",
    title: "Beckenkippen im Liegen",
    summary: "Kleine Bewegung für den unteren Rücken, ohne ihn zu verbiegen.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-back", "cat-hips", "cat-evening"],
    complaintIds: ["comp-back", "comp-hips"],
    defaultDurationSec: 90,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: 4,
      note: "Vier Wochen abends, danach an Tagen mit viel Sitzen behalten.",
    },
    steps: steps([
      ["lie", "Rückenlage, Knie aufgestellt, Füße am Boden."],
      ["cat", "Becken kippen: Lendenwirbel kurz zum Boden, dann die natürliche Kurve wieder erlauben.", 24],
      ["lie", "Still liegen und den Kontakt zum Boden spüren."],
    ]),
  }),
  exercise({
    id: "ex-calf-stretch",
    title: "Waden an der Wand",
    summary: "Eine Seite nach der anderen lang machen, ohne zu federn.",
    kind: "movement",
    categoryIds: ["cat-body", "cat-knees", "cat-mobility", "cat-daily"],
    complaintIds: ["comp-knees", "comp-hips"],
    defaultDurationSec: 80,
    suggestedRhythm: {
      kind: "days",
      daysOfWeek: [1, 3, 5],
      timesPerWeek: 3,
      recommendedWeeks: 4,
      note: "Drei Mal pro Woche, besonders nach langem Stehen oder Gehen in starren Schuhen.",
    },
    steps: steps([
      ["stand", "Hände an die Wand, ein Fuß weit hinten, hintere Ferse bleibt am Boden."],
      ["lunge", "Vorderes Knie beugen, hinteres Bein lang. 20 Sekunden, dann Seite wechseln.", 20],
      ["stand", "Ausschütteln. Waden dürfen warm sein, nicht brennen."],
    ]),
  }),
  exercise({
    id: "ex-shoulder-dump",
    title: "Schultern abladen",
    summary: "Ein Abendritual: hochziehen, fallen lassen, fertig.",
    kind: "movement",
    categoryIds: ["cat-daily", "cat-evening", "cat-shoulders"],
    complaintIds: ["comp-shoulders", "comp-stress", "comp-sleep"],
    defaultDurationSec: 70,
    suggestedRhythm: {
      kind: "daily",
      recommendedWeeks: null,
      note: "Abends, wenn der Tag noch in den Schultern hängt. Dauerhaft sinnvoll.",
    },
    steps: steps([
      ["stand", "Stehen oder sitzen. Einatmen, Schultern zu den Ohren."],
      ["chestOpen", "Ausatmen und die Schultern fallen lassen, schwerer als du denkst. Drei Runden.", 16],
      ["sit", "Arme hängen. Nichts weiter aufrichten."],
    ]),
  }),
  exercise({
    id: "ex-walk-attention",
    title: "Zwei Minuten gehen",
    summary: "Nur gehen und merken, dass die Füße den Boden treffen.",
    kind: "mind",
    categoryIds: ["cat-daily", "cat-mindfulness", "cat-pause"],
    complaintIds: ["comp-focus", "comp-stress"],
    defaultDurationSec: 120,
    suggestedRhythm: {
      kind: "every_n_days",
      everyNDays: 2,
      recommendedWeeks: null,
      note: "Alle zwei Tage, oder immer wenn der Kopf zu voll ist. Kein Trainingsspaziergang.",
    },
    steps: steps([
      ["stand", "Aufstehen. Kein Ziel, nur ein paar Meter."],
      ["tree", "Langsam gehen. Bei jedem Schritt: Ferse, Fußballen, Zehen.", 40],
      ["stand", "Stehen bleiben. Einen Atemzug, dann zurück zu dem, was als Nächstes da ist."],
    ]),
  }),
];

export const DEFAULT_PROFILE = {
  id: "solo" as const,
  displayName: "",
  reminderEnabled: true,
  reminderTime: "08:30",
  createdAt: nowIso(),
};
