import type { PoseId } from "./types";

export type JointAngles = {
  hipX: number;
  hipY: number;
  bodyTilt: number;
  torso: number;
  neck: number;
  jaw: number;
  leftUpperArm: number;
  leftForearm: number;
  leftHand: number;
  rightUpperArm: number;
  rightForearm: number;
  rightHand: number;
  leftThigh: number;
  leftShin: number;
  rightThigh: number;
  rightShin: number;
  shoulderLift: number;
  headShiftX: number;
  headShiftY: number;
  chest: number;
};

export const POSE_LABELS: Record<PoseId, string> = {
  stand: "Stand",
  reachUp: "Arme heben",
  fold: "Vorbeuge",
  squat: "Kniebeuge",
  lunge: "Ausfallschritt",
  plank: "Stütze",
  cobra: "Cobra",
  child: "Kind",
  cat: "Katze",
  cow: "Kuh",
  twist: "Drehung",
  sit: "Sitz",
  breathe: "Atmung",
  neckTilt: "Nacken",
  lie: "Liegen",
  warrior: "Krieger",
  tree: "Baum",
  hipOpen: "Hüfte",
  chestOpen: "Brustöffner",
  heart: "Herz",
  neckLeft: "Nacken links",
  neckRight: "Nacken rechts",
  shrug: "Schultern hoch",
  shouldersDown: "Schultern schwer",
  jawSoft: "Kiefer locker",
  gazeFar: "Blick in die Ferne",
  kneesUp: "Knie aufgestellt",
  pelvicTuck: "Becken kippen",
  pelvicArch: "Becken lösen",
  walkLeft: "Schritt links",
  walkRight: "Schritt rechts",
  wristsFlex: "Handgelenke beugen",
  wristsExtend: "Handgelenke strecken",
  shakeOut: "Ausschütteln",
  twistOther: "Drehung andere Seite",
  treeOther: "Baum andere Seite",
  lungeOther: "Ausfall andere Seite",
  breatheIn: "Einatmen",
  breatheOut: "Ausatmen",
  neckForward: "Nacken vorn",
  neckBack: "Nacken hinten",
  jawLeft: "Kiefer links",
  jawRight: "Kiefer rechts",
  warriorOther: "Krieger andere Seite",
  hipOpenOther: "Hüfte andere Seite",
  calfWall: "Wade an der Wand",
  calfWallOther: "Wade andere Seite",
  shoulderForward: "Schultern vorn",
  standInhale: "Einatmen im Stand",
  standExhale: "Ausatmen im Stand",
  lieInhale: "Einatmen im Liegen",
  lieHold: "Atem halten im Liegen",
  lieExhale: "Ausatmen im Liegen",
};

const stand: JointAngles = {
  hipX: 100,
  hipY: 148,
  bodyTilt: 0,
  torso: 0,
  neck: 0,
  jaw: 0,
  leftUpperArm: 18,
  leftForearm: 8,
  leftHand: 0,
  rightUpperArm: -18,
  rightForearm: -8,
  rightHand: 0,
  leftThigh: 10,
  leftShin: 4,
  rightThigh: -10,
  rightShin: -4,
  shoulderLift: 0,
  headShiftX: 0,
  headShiftY: 0,
  chest: 0,
};

const sit: JointAngles = {
  ...stand,
  hipX: 104,
  hipY: 188,
  torso: -6,
  neck: -4,
  leftUpperArm: 28,
  leftForearm: 36,
  rightUpperArm: -28,
  rightForearm: -36,
  leftThigh: 86,
  leftShin: 78,
  rightThigh: -86,
  rightShin: -78,
};

const lie: JointAngles = {
  ...stand,
  hipX: 108,
  hipY: 196,
  bodyTilt: 90,
  torso: 0,
  neck: -6,
  leftUpperArm: 8,
  leftForearm: 12,
  rightUpperArm: -8,
  rightForearm: -12,
  leftThigh: 8,
  leftShin: 4,
  rightThigh: -8,
  rightShin: -4,
};

function j(over: Partial<JointAngles>, base: JointAngles = stand): JointAngles {
  return { ...base, ...over };
}

export const POSES: Record<PoseId, JointAngles> = {
  stand,
  sit,
  lie,
  reachUp: j({
    leftUpperArm: 168,
    leftForearm: 8,
    rightUpperArm: -168,
    rightForearm: -8,
    neck: -6,
    headShiftY: -4,
    chest: 4,
  }),
  fold: j({
    hipY: 158,
    torso: 92,
    neck: 12,
    headShiftY: 8,
    leftUpperArm: 160,
    leftForearm: 20,
    rightUpperArm: -160,
    rightForearm: -20,
    leftThigh: 8,
    rightThigh: -8,
  }),
  squat: j({
    hipY: 176,
    torso: 18,
    leftUpperArm: 70,
    leftForearm: 40,
    rightUpperArm: -70,
    rightForearm: -40,
    leftThigh: 78,
    leftShin: -78,
    rightThigh: -78,
    rightShin: 78,
  }),
  lunge: j({
    hipX: 108,
    hipY: 156,
    torso: 8,
    leftUpperArm: 150,
    rightUpperArm: -20,
    leftThigh: 55,
    leftShin: -20,
    rightThigh: -70,
    rightShin: 8,
  }),
  plank: j({
    hipX: 108,
    hipY: 168,
    bodyTilt: 82,
    torso: 4,
    neck: -8,
    leftUpperArm: 95,
    leftForearm: 8,
    rightUpperArm: 95,
    rightForearm: 8,
    leftThigh: 8,
    leftShin: 4,
    rightThigh: -8,
    rightShin: -4,
  }),
  cobra: j({
    hipX: 112,
    hipY: 198,
    bodyTilt: 18,
    torso: -38,
    neck: -18,
    headShiftY: -6,
    chest: 8,
    leftUpperArm: 110,
    leftForearm: 55,
    rightUpperArm: -110,
    rightForearm: -55,
    leftThigh: 86,
    leftShin: 4,
    rightThigh: -86,
    rightShin: -4,
  }),
  child: j({
    hipX: 108,
    hipY: 196,
    bodyTilt: 8,
    torso: 72,
    neck: 16,
    headShiftY: 6,
    leftUpperArm: 168,
    leftForearm: 12,
    rightUpperArm: -168,
    rightForearm: -12,
    leftThigh: 70,
    leftShin: 70,
    rightThigh: -70,
    rightShin: -70,
  }),
  cat: j({
    hipX: 100,
    hipY: 168,
    bodyTilt: 8,
    torso: 28,
    neck: 22,
    headShiftY: 10,
    chest: -6,
    leftUpperArm: 92,
    leftForearm: 8,
    rightUpperArm: -92,
    rightForearm: -8,
    leftThigh: 88,
    leftShin: 8,
    rightThigh: -88,
    rightShin: -8,
  }),
  cow: j({
    hipX: 100,
    hipY: 172,
    bodyTilt: 6,
    torso: -18,
    neck: -22,
    headShiftY: -8,
    chest: 8,
    leftUpperArm: 88,
    leftForearm: 10,
    rightUpperArm: -88,
    rightForearm: -10,
    leftThigh: 86,
    leftShin: 6,
    rightThigh: -86,
    rightShin: -6,
  }),
  twist: j(
    {
      torso: 10,
      neck: 32,
      headShiftX: 10,
      leftUpperArm: 70,
      leftForearm: 55,
      rightUpperArm: -130,
      rightForearm: -20,
    },
    sit,
  ),
  breathe: j(
    {
      torso: -4,
      neck: -2,
      chest: 3,
      leftUpperArm: 42,
      leftForearm: 48,
      rightUpperArm: -42,
      rightForearm: -48,
    },
    sit,
  ),
  neckTilt: j({
    neck: 32,
    headShiftX: 8,
    leftUpperArm: 8,
    rightUpperArm: -8,
  }),
  warrior: j({
    hipX: 100,
    hipY: 150,
    torso: -4,
    chest: 5,
    leftUpperArm: 172,
    leftForearm: 6,
    rightUpperArm: -172,
    rightForearm: -6,
    leftThigh: 42,
    leftShin: -8,
    rightThigh: -78,
    rightShin: 10,
  }),
  tree: j({
    leftUpperArm: 150,
    leftForearm: 40,
    rightUpperArm: -150,
    rightForearm: -40,
    leftThigh: 8,
    leftShin: 4,
    rightThigh: -48,
    rightShin: 70,
  }),
  hipOpen: j(
    {
      hipX: 108,
      torso: -8,
      neck: -4,
      leftUpperArm: 16,
      leftForearm: 10,
      rightUpperArm: -16,
      rightForearm: -10,
      leftThigh: 70,
      leftShin: 55,
      rightThigh: -95,
      rightShin: 20,
    },
    sit,
  ),
  chestOpen: j({
    torso: -12,
    neck: -8,
    headShiftY: -4,
    chest: 10,
    shoulderLift: -4,
    leftUpperArm: -62,
    leftForearm: -28,
    rightUpperArm: 62,
    rightForearm: 28,
  }),
  heart: j({
    leftUpperArm: 42,
    leftForearm: 58,
    leftHand: 18,
    rightUpperArm: -18,
    rightForearm: -8,
    neck: -4,
    chest: 3,
  }),
  neckLeft: j({
    neck: 38,
    headShiftX: 12,
    leftUpperArm: 6,
    rightUpperArm: -10,
    shoulderLift: -2,
  }),
  neckRight: j({
    neck: -38,
    headShiftX: -12,
    leftUpperArm: 10,
    rightUpperArm: -6,
    shoulderLift: -2,
  }),
  shrug: j({
    neck: 8,
    headShiftY: 6,
    shoulderLift: 16,
    leftUpperArm: 12,
    leftForearm: 6,
    rightUpperArm: -12,
    rightForearm: -6,
  }),
  shouldersDown: j({
    neck: -6,
    headShiftY: -2,
    shoulderLift: -6,
    leftUpperArm: 8,
    leftForearm: 4,
    rightUpperArm: -8,
    rightForearm: -4,
  }),
  jawSoft: j(
    {
      neck: -8,
      jaw: 14,
      headShiftY: 4,
      leftUpperArm: 12,
      leftForearm: 8,
      rightUpperArm: -12,
      rightForearm: -8,
    },
    sit,
  ),
  gazeFar: j(
    {
      torso: -6,
      neck: -14,
      headShiftY: -8,
      leftUpperArm: 16,
      leftForearm: 22,
      rightUpperArm: -16,
      rightForearm: -22,
    },
    sit,
  ),
  kneesUp: j({
    hipX: 108,
    hipY: 198,
    bodyTilt: 90,
    neck: -4,
    leftUpperArm: 12,
    leftForearm: 8,
    rightUpperArm: -12,
    rightForearm: -8,
    leftThigh: -55,
    leftShin: 70,
    rightThigh: 55,
    rightShin: -70,
  }),
  pelvicTuck: j({
    hipX: 108,
    hipY: 200,
    bodyTilt: 96,
    torso: 10,
    neck: 2,
    leftUpperArm: 12,
    leftForearm: 8,
    rightUpperArm: -12,
    rightForearm: -8,
    leftThigh: -48,
    leftShin: 62,
    rightThigh: 48,
    rightShin: -62,
  }),
  pelvicArch: j({
    hipX: 108,
    hipY: 196,
    bodyTilt: 84,
    torso: -10,
    neck: -8,
    leftUpperArm: 12,
    leftForearm: 8,
    rightUpperArm: -12,
    rightForearm: -8,
    leftThigh: -62,
    leftShin: 78,
    rightThigh: 62,
    rightShin: -78,
  }),
  walkLeft: j({
    hipX: 110,
    bodyTilt: 5,
    leftUpperArm: -42,
    leftForearm: -18,
    rightUpperArm: 52,
    rightForearm: 22,
    leftThigh: 46,
    leftShin: -16,
    rightThigh: -56,
    rightShin: 32,
  }),
  walkRight: j({
    hipX: 90,
    bodyTilt: -5,
    leftUpperArm: 52,
    leftForearm: 22,
    rightUpperArm: -42,
    rightForearm: -18,
    leftThigh: -56,
    leftShin: 32,
    rightThigh: 46,
    rightShin: -16,
  }),
  wristsFlex: j({
    leftUpperArm: 88,
    leftForearm: 8,
    leftHand: 70,
    rightUpperArm: -88,
    rightForearm: -8,
    rightHand: -70,
  }),
  wristsExtend: j({
    leftUpperArm: 88,
    leftForearm: 22,
    leftHand: -62,
    rightUpperArm: -88,
    rightForearm: -22,
    rightHand: 62,
  }),
  shakeOut: j({
    leftUpperArm: 78,
    leftForearm: 48,
    leftHand: 42,
    rightUpperArm: -34,
    rightForearm: -58,
    rightHand: -38,
    shoulderLift: 4,
  }),
  twistOther: j(
    {
      torso: -10,
      neck: -32,
      headShiftX: -10,
      leftUpperArm: 130,
      leftForearm: 20,
      rightUpperArm: -70,
      rightForearm: -55,
    },
    sit,
  ),
  treeOther: j({
    leftUpperArm: 150,
    leftForearm: 40,
    rightUpperArm: -150,
    rightForearm: -40,
    leftThigh: 48,
    leftShin: -70,
    rightThigh: -8,
    rightShin: -4,
  }),
  lungeOther: j({
    hipX: 92,
    hipY: 156,
    torso: 8,
    leftUpperArm: 20,
    rightUpperArm: -150,
    leftThigh: 70,
    leftShin: -8,
    rightThigh: -55,
    rightShin: 20,
  }),
  breatheIn: j(
    {
      torso: -10,
      neck: -6,
      chest: 10,
      leftUpperArm: 52,
      leftForearm: 40,
      rightUpperArm: -52,
      rightForearm: -40,
    },
    sit,
  ),
  breatheOut: j(
    {
      torso: 4,
      neck: 2,
      chest: -4,
      leftUpperArm: 22,
      leftForearm: 28,
      rightUpperArm: -22,
      rightForearm: -28,
    },
    sit,
  ),
  neckForward: j({
    neck: 4,
    torso: 8,
    headShiftY: 16,
    leftUpperArm: 8,
    rightUpperArm: -8,
  }),
  neckBack: j({
    neck: -8,
    torso: -6,
    headShiftY: -12,
    leftUpperArm: 8,
    rightUpperArm: -8,
  }),
  jawLeft: j(
    {
      neck: 12,
      jaw: 12,
      headShiftX: 14,
      headShiftY: 3,
      leftUpperArm: 12,
      leftForearm: 8,
      rightUpperArm: -12,
      rightForearm: -8,
    },
    sit,
  ),
  jawRight: j(
    {
      neck: -12,
      jaw: 12,
      headShiftX: -14,
      headShiftY: 3,
      leftUpperArm: 12,
      leftForearm: 8,
      rightUpperArm: -12,
      rightForearm: -8,
    },
    sit,
  ),
  warriorOther: j({
    hipX: 100,
    hipY: 150,
    torso: -4,
    chest: 5,
    leftUpperArm: 172,
    leftForearm: 6,
    rightUpperArm: -172,
    rightForearm: -6,
    leftThigh: 78,
    leftShin: -10,
    rightThigh: -42,
    rightShin: 8,
  }),
  hipOpenOther: j(
    {
      hipX: 100,
      torso: -8,
      neck: -4,
      leftUpperArm: 16,
      leftForearm: 10,
      rightUpperArm: -16,
      rightForearm: -10,
      leftThigh: 95,
      leftShin: -20,
      rightThigh: -70,
      rightShin: -55,
    },
    sit,
  ),
  calfWall: j({
    hipX: 106,
    hipY: 152,
    torso: 14,
    chest: 2,
    leftUpperArm: 108,
    leftForearm: 28,
    leftHand: -8,
    rightUpperArm: -108,
    rightForearm: -28,
    rightHand: 8,
    leftThigh: 8,
    leftShin: 2,
    rightThigh: -58,
    rightShin: 18,
  }),
  calfWallOther: j({
    hipX: 94,
    hipY: 152,
    torso: 14,
    chest: 2,
    leftUpperArm: 108,
    leftForearm: 28,
    leftHand: -8,
    rightUpperArm: -108,
    rightForearm: -28,
    rightHand: 8,
    leftThigh: 58,
    leftShin: -18,
    rightThigh: -8,
    rightShin: -2,
  }),
  shoulderForward: j({
    torso: 14,
    neck: 8,
    headShiftY: 4,
    chest: -6,
    shoulderLift: 6,
    leftUpperArm: 48,
    leftForearm: 22,
    rightUpperArm: -48,
    rightForearm: -22,
  }),
  standInhale: j({
    torso: -10,
    neck: -6,
    chest: 10,
    shoulderLift: 2,
    leftUpperArm: 28,
    leftForearm: 12,
    rightUpperArm: -28,
    rightForearm: -12,
  }),
  standExhale: j({
    torso: 4,
    neck: 2,
    chest: -3,
    shoulderLift: -4,
    leftUpperArm: 10,
    leftForearm: 6,
    rightUpperArm: -10,
    rightForearm: -6,
  }),
  lieInhale: j(
    {
      torso: -8,
      neck: -8,
      chest: 8,
      leftUpperArm: 22,
      leftForearm: 10,
      rightUpperArm: -22,
      rightForearm: -10,
    },
    lie,
  ),
  lieHold: j(
    {
      torso: -4,
      neck: -4,
      chest: 5,
      leftUpperArm: 14,
      leftForearm: 10,
      rightUpperArm: -14,
      rightForearm: -10,
    },
    lie,
  ),
  lieExhale: j(
    {
      torso: 4,
      neck: -2,
      chest: -3,
      leftUpperArm: 6,
      leftForearm: 8,
      rightUpperArm: -6,
      rightForearm: -8,
    },
    lie,
  ),
};

export const POSE_IDS = Object.keys(POSES) as PoseId[];

export function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

export function lerpPose(a: JointAngles, b: JointAngles, t: number): JointAngles {
  const keys = Object.keys({ ...a, ...b }) as (keyof JointAngles)[];
  const out = { ...a };
  for (const key of keys) {
    out[key] = lerp(a[key] ?? 0, b[key] ?? 0, t);
  }
  return out;
}
