import type { PoseId } from "./types";

export type JointAngles = {
  hipX: number;
  hipY: number;
  bodyTilt: number;
  torso: number;
  neck: number;
  leftUpperArm: number;
  leftForearm: number;
  rightUpperArm: number;
  rightForearm: number;
  leftThigh: number;
  leftShin: number;
  rightThigh: number;
  rightShin: number;
};

export const POSE_LABELS: Record<PoseId, string> = {
  stand: "Stand",
  reachUp: "Arme heben",
  fold: "Vorbeuge",
  squat: "Kniebeuge",
  lunge: "Ausfallschritt",
  plank: "Stütze",
  cobra: "Cobra",
  child: "Kind",
  cat: "Katze",
  cow: "Kuh",
  twist: "Drehung",
  sit: "Sitz",
  breathe: "Atmung",
  neckTilt: "Nacken",
  lie: "Liegen",
  warrior: "Krieger",
  tree: "Baum",
  hipOpen: "Hüfte",
  chestOpen: "Brustöffner",
  heart: "Herz",
};

const base: JointAngles = {
  hipX: 100,
  hipY: 148,
  bodyTilt: 0,
  torso: 0,
  neck: 0,
  leftUpperArm: 18,
  leftForearm: 8,
  rightUpperArm: -18,
  rightForearm: -8,
  leftThigh: 10,
  leftShin: 4,
  rightThigh: -10,
  rightShin: -4,
};

export const POSES: Record<PoseId, JointAngles> = {
  stand: base,
  reachUp: {
    ...base,
    leftUpperArm: 168,
    leftForearm: 8,
    rightUpperArm: -168,
    rightForearm: -8,
    neck: -6,
  },
  fold: {
    ...base,
    hipY: 158,
    torso: 92,
    neck: 12,
    leftUpperArm: 160,
    leftForearm: 20,
    rightUpperArm: -160,
    rightForearm: -20,
    leftThigh: 8,
    rightThigh: -8,
  },
  squat: {
    ...base,
    hipY: 176,
    torso: 18,
    leftUpperArm: 70,
    leftForearm: 40,
    rightUpperArm: -70,
    rightForearm: -40,
    leftThigh: 78,
    leftShin: -78,
    rightThigh: -78,
    rightShin: 78,
  },
  lunge: {
    ...base,
    hipX: 108,
    hipY: 156,
    torso: 8,
    leftUpperArm: 150,
    rightUpperArm: -20,
    leftThigh: 55,
    leftShin: -20,
    rightThigh: -70,
    rightShin: 8,
  },
  plank: {
    hipX: 108,
    hipY: 168,
    bodyTilt: 82,
    torso: 4,
    neck: -8,
    leftUpperArm: 95,
    leftForearm: 8,
    rightUpperArm: 95,
    rightForearm: 8,
    leftThigh: 8,
    leftShin: 4,
    rightThigh: -8,
    rightShin: -4,
  },
  cobra: {
    hipX: 112,
    hipY: 198,
    bodyTilt: 18,
    torso: -38,
    neck: -18,
    leftUpperArm: 110,
    leftForearm: 55,
    rightUpperArm: -110,
    rightForearm: -55,
    leftThigh: 86,
    leftShin: 4,
    rightThigh: -86,
    rightShin: -4,
  },
  child: {
    hipX: 108,
    hipY: 196,
    bodyTilt: 8,
    torso: 72,
    neck: 16,
    leftUpperArm: 168,
    leftForearm: 12,
    rightUpperArm: -168,
    rightForearm: -12,
    leftThigh: 70,
    leftShin: 70,
    rightThigh: -70,
    rightShin: -70,
  },
  cat: {
    hipX: 100,
    hipY: 168,
    bodyTilt: 8,
    torso: 28,
    neck: 22,
    leftUpperArm: 92,
    leftForearm: 8,
    rightUpperArm: -92,
    rightForearm: -8,
    leftThigh: 88,
    leftShin: 8,
    rightThigh: -88,
    rightShin: -8,
  },
  cow: {
    hipX: 100,
    hipY: 172,
    bodyTilt: 6,
    torso: -18,
    neck: -22,
    leftUpperArm: 88,
    leftForearm: 10,
    rightUpperArm: -88,
    rightForearm: -10,
    leftThigh: 86,
    leftShin: 6,
    rightThigh: -86,
    rightShin: -6,
  },
  twist: {
    ...base,
    torso: 8,
    neck: 28,
    leftUpperArm: 70,
    leftForearm: 55,
    rightUpperArm: -130,
    rightForearm: -20,
  },
  sit: {
    hipX: 104,
    hipY: 188,
    bodyTilt: 0,
    torso: -6,
    neck: -4,
    leftUpperArm: 28,
    leftForearm: 36,
    rightUpperArm: -28,
    rightForearm: -36,
    leftThigh: 86,
    leftShin: 78,
    rightThigh: -86,
    rightShin: -78,
  },
  breathe: {
    hipX: 104,
    hipY: 188,
    bodyTilt: 0,
    torso: -4,
    neck: -2,
    leftUpperArm: 42,
    leftForearm: 48,
    rightUpperArm: -42,
    rightForearm: -48,
    leftThigh: 86,
    leftShin: 78,
    rightThigh: -86,
    rightShin: -78,
  },
  neckTilt: {
    ...base,
    neck: 32,
    leftUpperArm: 8,
    rightUpperArm: -8,
  },
  lie: {
    hipX: 108,
    hipY: 196,
    bodyTilt: 90,
    torso: 0,
    neck: -6,
    leftUpperArm: 8,
    leftForearm: 12,
    rightUpperArm: -8,
    rightForearm: -12,
    leftThigh: 8,
    leftShin: 4,
    rightThigh: -8,
    rightShin: -4,
  },
  warrior: {
    hipX: 100,
    hipY: 150,
    bodyTilt: 0,
    torso: -4,
    neck: 0,
    leftUpperArm: 172,
    leftForearm: 6,
    rightUpperArm: -172,
    rightForearm: -6,
    leftThigh: 42,
    leftShin: -8,
    rightThigh: -78,
    rightShin: 10,
  },
  tree: {
    ...base,
    leftUpperArm: 150,
    leftForearm: 40,
    rightUpperArm: -150,
    rightForearm: -40,
    leftThigh: 8,
    leftShin: 4,
    rightThigh: -48,
    rightShin: 70,
  },
  hipOpen: {
    hipX: 108,
    hipY: 186,
    bodyTilt: 0,
    torso: -8,
    neck: -4,
    leftUpperArm: 16,
    leftForearm: 10,
    rightUpperArm: -16,
    rightForearm: -10,
    leftThigh: 70,
    leftShin: 55,
    rightThigh: -95,
    rightShin: 20,
  },
  chestOpen: {
    ...base,
    torso: -10,
    neck: -8,
    leftUpperArm: -55,
    leftForearm: -20,
    rightUpperArm: 55,
    rightForearm: 20,
  },
  heart: {
    ...base,
    leftUpperArm: 42,
    leftForearm: 58,
    rightUpperArm: -18,
    rightForearm: -8,
    neck: -4,
  },
};

export const POSE_IDS = Object.keys(POSES) as PoseId[];

export function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

export function lerpPose(a: JointAngles, b: JointAngles, t: number): JointAngles {
  const keys = Object.keys(a) as (keyof JointAngles)[];
  const out = { ...a };
  for (const key of keys) {
    out[key] = lerp(a[key], b[key], t);
  }
  return out;
}
