-- Generated catalog seed. Re-run: npx tsx scripts/generate-seed.ts

insert into public.categories (id, name, slug, parent_id, description, is_system)
values
('cat-body', 'Körper', 'koerper', null, 'Bewegung, Kraft, Haltung.', true),
('cat-mind', 'Geist', 'geist', null, 'Mantras, Meditation, Aufmerksamkeit.', true),
('cat-daily', 'Alltag', 'alltag', null, 'Kurze Rituale für Morgen, Pause und Abend.', true),
('cat-mobility', 'Beweglichkeit', 'beweglichkeit', 'cat-body', 'Sanftes Öffnen und Fließen.', true),
('cat-strength', 'Kraft', 'kraft', 'cat-body', 'Stabile, einfache Kraftreize.', true),
('cat-posture', 'Haltung', 'haltung', 'cat-body', 'Aufrichten ohne Verkrampfen.', true),
('cat-breath', 'Atmung', 'atmung', 'cat-body', 'Atem als Übung, nicht nur Beiwerk.', true),
('cat-neck', 'Nacken', 'nacken', 'cat-body', 'Nacken und Halswirbelsäule.', true),
('cat-shoulders', 'Schultern', 'schultern', 'cat-body', 'Schultergürtel und Brustkorb.', true),
('cat-back', 'Rücken', 'ruecken', 'cat-body', 'Lenden- und Brustwirbelsäule.', true),
('cat-hips', 'Hüfte', 'huefte', 'cat-body', 'Becken, Hüftbeuger, Gesäß.', true),
('cat-knees', 'Knie', 'knie', 'cat-body', 'Kniegelenke und Beinachsen.', true),
('cat-mantras', 'Mantras', 'mantras', 'cat-mind', 'Sätze, die du regelmäßig sagst oder denkst.', true),
('cat-meditation', 'Meditation', 'meditation', 'cat-mind', 'Stille, Scan, Sitzen.', true),
('cat-mindfulness', 'Achtsamkeit', 'achtsamkeit', 'cat-mind', 'Kurze Anker im Alltag.', true),
('cat-morning', 'Morgen', 'morgen', 'cat-daily', 'Sanfter Start.', true),
('cat-pause', 'Pause', 'pause', 'cat-daily', 'Zwischendurch, oft am Schreibtisch.', true),
('cat-evening', 'Abend', 'abend', 'cat-daily', 'Runterkommen vor dem Schlaf.', true)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  parent_id = excluded.parent_id,
  description = excluded.description,
  is_system = excluded.is_system;

insert into public.complaints (id, name, summary, hint)
values
('comp-neck', 'Nackensteifheit', 'Verspannter Nacken, Kopf fühlt sich schwer an.', 'Kleine Bewegungen, oft, statt einmal hart zu dehnen.'),
('comp-shoulders', 'Hängende Schultern', 'Schultern nach vorn, Brustkorb eng.', 'Öffnen und absenken, nicht nur nach hinten ziehen.'),
('comp-back', 'Rückenschmerzen', 'Untere oder mittlere Wirbelsäule protestiert.', 'Wechsel aus Beugen und Strecken, nie in den Schmerz hinein.'),
('comp-hips', 'Enge Hüfte', 'Langes Sitzen, Hüftbeuger kurz.', 'Täglich kurz öffnen wirkt oft besser als selten lang.'),
('comp-knees', 'Knieunruhe', 'Knie fühlen sich unbequem oder instabil an.', 'Kraft um das Gelenk, kein übertriebenes Dehnen.'),
('comp-stress', 'Stress & Unruhe', 'Gedanken rasen, Körper ist an.', 'Atem und Mantra zuerst, Bewegung nur so viel, wie der Tag noch trägt.'),
('comp-sleep', 'Schwer einschlafen', 'Der Tag geht im Kopf weiter.', 'Atem und Mantra vor dem Liegen, kein Training spätabends.'),
('comp-focus', 'Zerstreutheit', 'Du fängst vieles an und verlierst den Faden.', 'Kurze Anker, die du wirklich schaffst.')
on conflict (id) do update set
  name = excluded.name,
  summary = excluded.summary,
  hint = excluded.hint;

insert into public.exercises (
  id, owner_id, title, summary, kind, category_ids, complaint_ids, steps,
  default_duration_sec, default_reps, suggested_rhythm, source, is_system, created_at, updated_at
)
values
('ex-neck-circles', null, 'Nacken langsam kreisen', 'Kleine Kreise, die den Nacken erinnern, dass er sich bewegen darf.', 'movement', array['cat-body', 'cat-neck', 'cat-mobility', 'cat-pause']::text[], array['comp-neck', 'comp-shoulders']::text[], '[{"pose":"stand","text":"Stell dich oder setz dich aufrecht hin. Schultern schwer, Kiefer locker.","durationSec":8},{"pose":"neckTilt","text":"Neige das Ohr zur Schulter. Nicht ziehen, nur nachgeben.","durationSec":10},{"pose":"neckTilt","text":"Kleine Kreise, halb so groß wie du denkst. Atme dabei ruhig.","durationSec":20},{"pose":"stand","text":"Komm zur Mitte zurück. Spüre, ob der Kopf leichter sitzt.","durationSec":8}]'::jsonb, 90, null, '{"kind":"daily","recommendedWeeks":null,"note":"Jeden Tag 1–2 Minuten, besonders nach Bildschirmarbeit. Das darf dauerhaft im Plan bleiben."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-shoulder-rolls', null, 'Schulterkreisen', 'Die Schultern nach hinten-unten schicken, statt sie am Ohr zu parken.', 'movement', array['cat-body', 'cat-shoulders', 'cat-posture', 'cat-pause']::text[], array['comp-shoulders', 'comp-neck']::text[], '[{"pose":"stand","text":"Arme hängen lassen. Spüre das Gewicht der Hände.","durationSec":8},{"pose":"chestOpen","text":"Schultern nach vorn, hoch, hinten, unten – große, langsame Kreise.","durationSec":16},{"pose":"reachUp","text":"Einmal einatmen, Arme heben, ausatmen, Schultern fallen lassen.","durationSec":8},{"pose":"stand","text":"Prüfe: Sind die Schultern näher an den Hüften als am Kiefer?","durationSec":8}]'::jsonb, 80, null, '{"kind":"daily","recommendedWeeks":null,"note":"Unter der Woche mehrmals kurz, nicht einmal lang."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-cat-cow', null, 'Katze und Kuh', 'Die Wirbelsäule wellen, statt sie starr zu halten.', 'movement', array['cat-body', 'cat-back', 'cat-mobility', 'cat-morning']::text[], array['comp-back', 'comp-hips']::text[], '[{"pose":"cat","text":"Vierfüßler: Hände unter Schultern, Knie unter Hüften. Rund den Rücken, Blick zum Bauch.","durationSec":10},{"pose":"cow","text":"Mit der Einatmung Brustbein nach vorn, Steißbein nach oben, Blick leicht heben.","durationSec":10},{"pose":"cat","text":"Mit der Ausatmung wieder runden. Bewege dich im Atem, nicht gegen ihn.","durationSec":16},{"pose":"child","text":"Setz dich zu den Fersen, wenn du fertig bist, und ruhe kurz.","durationSec":8}]'::jsonb, 120, null, '{"kind":"daily","recommendedWeeks":6,"note":"Sechs Wochen täglich, danach mindestens an Bürotagen behalten."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-cobra', null, 'Sanfte Cobra', 'Eine kleine Rückbeuge, die den oberen Rücken weckt.', 'movement', array['cat-body', 'cat-back', 'cat-posture', 'cat-mobility']::text[], array['comp-back', 'comp-shoulders']::text[], '[{"pose":"lie","text":"Bauchlage, Stirn kurz abgelegt, Hände neben der Brust.","durationSec":8},{"pose":"cobra","text":"Zieh die Brust nach vorn-oben. Die Unterarme dürfen bleiben. Nacken lang.","durationSec":16},{"pose":"lie","text":"Senke dich ab und spüre die Länge der Vorderseite.","durationSec":8}]'::jsonb, 90, null, '{"kind":"days","daysOfWeek":[1,3,5,0],"timesPerWeek":4,"recommendedWeeks":8,"note":"Vier Mal pro Woche. Am Abend weicher halten als am Morgen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-child', null, 'Kindeshaltung', 'Eine Pause in Form einer Haltung.', 'movement', array['cat-body', 'cat-back', 'cat-evening', 'cat-mobility']::text[], array['comp-back', 'comp-stress']::text[], '[{"pose":"sit","text":"Knie weit oder eng, wie es für deine Hüfte freundlich ist.","durationSec":8},{"pose":"child","text":"Gesäß zu den Fersen, Arme nach vorn oder neben dem Körper. Atme in den Rücken.","durationSec":30},{"pose":"sit","text":"Rolle dich langsam auf, Kopf zuletzt.","durationSec":8}]'::jsonb, 90, null, '{"kind":"daily","recommendedWeeks":null,"note":"Immer dann, wenn der Tag zu voll wurde. Auch 45 Sekunden zählen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-forward-fold', null, 'Stehende Vorbeuge', 'Der Oberkörper darf schwer werden, die Beine tragen.', 'movement', array['cat-body', 'cat-mobility', 'cat-back', 'cat-morning']::text[], array['comp-back', 'comp-stress']::text[], '[{"pose":"stand","text":"Füße hüftbreit. Einatmen, Länge im Rücken.","durationSec":8},{"pose":"fold","text":"Ausatmen, Oberkörper hängen lassen. Kopf schwer, Knie gebeugt ist richtig.","durationSec":20},{"pose":"reachUp","text":"Mit leichtem Schwung wieder aufrichten, Arme mitnehmen.","durationSec":8},{"pose":"stand","text":"Stehen bleiben und nachspüren.","durationSec":8}]'::jsonb, 70, null, '{"kind":"weekdays","recommendedWeeks":4,"note":"Unter der Woche nach dem Aufstehen. Knie dürfen weich bleiben."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-squat', null, 'Langsame Kniebeuge', 'Kraft für Beine und eine klarere Beinachse.', 'movement', array['cat-body', 'cat-strength', 'cat-knees']::text[], array['comp-knees', 'comp-hips']::text[], '[{"pose":"stand","text":"Füße etwas breiter als die Hüfte, Fußspitzen leicht außen.","durationSec":8},{"pose":"squat","text":"Senke dich ab, als würdest du dich auf einen Stuhl setzen. Knie zeigen über die Füße.","durationSec":12},{"pose":"stand","text":"Drück dich über die ganze Fußsohle wieder hoch. 8 ruhige Wiederholungen.","durationSec":8}]'::jsonb, 100, 8, '{"kind":"days","daysOfWeek":[1,3,5],"timesPerWeek":3,"recommendedWeeks":8,"note":"Drei Mal pro Woche. Qualität vor Tiefe."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-lunge', null, 'Ausfallschritt zum Hüftbeuger', 'Das Gegenmittel zum Sitzen: vordere Hüfte lang.', 'movement', array['cat-body', 'cat-hips', 'cat-mobility', 'cat-pause']::text[], array['comp-hips', 'comp-back']::text[], '[{"pose":"stand","text":"Großer Schritt nach hinten mit dem rechten Fuß.","durationSec":8},{"pose":"lunge","text":"Hintere Ferse hebt, vordere Hüfte sinkt. Schambein leicht nach vorn-oben.","durationSec":20},{"pose":"stand","text":"Seite wechseln und gleich lang bleiben.","durationSec":8}]'::jsonb, 120, null, '{"kind":"daily","recommendedWeeks":4,"note":"Vier Wochen täglich je Seite, danach an Sitz-Tagen behalten."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-hip-open', null, 'Sitzender Hüftöffner', 'Eine Seite der Hüfte nach der anderen weich machen.', 'movement', array['cat-body', 'cat-hips', 'cat-evening', 'cat-mobility']::text[], array['comp-hips', 'comp-back']::text[], '[{"pose":"sit","text":"Aufrecht sitzen, ein Fuß vor dem anderen oder Fußgelenk auf dem Oberschenkel, wenn das Knie einverstanden ist.","durationSec":8},{"pose":"hipOpen","text":"Kipp das Becken leicht nach vorn. Atme in die Leiste.","durationSec":30},{"pose":"sit","text":"Wechsel die Seite. Nicht ziehen, nur bleiben.","durationSec":8}]'::jsonb, 150, null, '{"kind":"daily","recommendedWeeks":6,"note":"Abends 2 Minuten. Sechs Wochen sind ein guter erster Block."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-plank', null, 'Stütze auf den Unterarmen', 'Mitte anschalten, ohne den Atem anzuhalten.', 'movement', array['cat-body', 'cat-strength', 'cat-posture']::text[], array['comp-back']::text[], '[{"pose":"plank","text":"Unterarme parallel, Becken weder durchhängen noch spitz nach oben. Schau auf den Boden.","durationSec":20},{"pose":"child","text":"Knie ab, kurz in die Kindeshaltung und nachspüren.","durationSec":8}]'::jsonb, 40, null, '{"kind":"days","daysOfWeek":[2,4,6],"timesPerWeek":3,"recommendedWeeks":8,"note":"Drei Mal pro Woche, 20–40 Sekunden. Länger nur, wenn die Form bleibt."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-tree', null, 'Baum', 'Eine Minute Balance, die den Tag sammelt.', 'movement', array['cat-body', 'cat-strength', 'cat-mindfulness', 'cat-morning']::text[], array['comp-focus', 'comp-knees']::text[], '[{"pose":"stand","text":"Finde einen Punkt zum Anschauen. Gewicht auf den linken Fuß.","durationSec":8},{"pose":"tree","text":"Rechte Fußsohle an Waden oder Oberschenkel, nie gegen das Knie. Hände vor der Brust oder nach oben.","durationSec":20},{"pose":"stand","text":"Seite wechseln. Wenn du fällst, bist du mittendrin, nicht draußen.","durationSec":8}]'::jsonb, 80, null, '{"kind":"daily","recommendedWeeks":null,"note":"Morgens je Seite 20–30 Sekunden. Immer erlaubt, die Zehen am Boden zu lassen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-warrior', null, 'Kriegerlicht', 'Standfestigkeit mit Länge in den Armen.', 'movement', array['cat-body', 'cat-strength', 'cat-hips', 'cat-morning']::text[], array['comp-hips', 'comp-focus']::text[], '[{"pose":"stand","text":"Weiter Ausfallschritt, hintere Ferse verankert, soweit es geht.","durationSec":8},{"pose":"warrior","text":"Vorderes Knie über dem Fuß, Arme hoch oder zur Seite. Atme in die Breite der Brust.","durationSec":20},{"pose":"stand","text":"Aufrichten und die andere Seite.","durationSec":8}]'::jsonb, 90, null, '{"kind":"days","daysOfWeek":[1,3,5],"timesPerWeek":3,"recommendedWeeks":4,"note":"Drei Mal pro Woche als Mini-Kraft und Fokus."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-chest-open', null, 'Brustöffner an der Tür', 'Den vorderen Schultergürtel erinnern, dass er länger sein darf.', 'movement', array['cat-body', 'cat-shoulders', 'cat-posture', 'cat-pause']::text[], array['comp-shoulders', 'comp-neck']::text[], '[{"pose":"stand","text":"Stell dich in einen Türrahmen oder verschränke die Hände hinter dem Rücken.","durationSec":8},{"pose":"chestOpen","text":"Brustbein hebt sich, Schulterblätter gleiten zur Gesäßtasche. Nacken bleibt lang.","durationSec":20},{"pose":"stand","text":"Lass los und schüttle die Arme aus.","durationSec":8}]'::jsonb, 70, null, '{"kind":"weekdays","recommendedWeeks":null,"note":"An Bürotagen, nach längeren Calls. Dauerhaft sinnvoll."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-twist', null, 'Sitzende Drehung', 'Eine ruhige Rotation für die Brustwirbelsäule.', 'movement', array['cat-body', 'cat-back', 'cat-mobility', 'cat-pause']::text[], array['comp-back']::text[], '[{"pose":"sit","text":"Sitzbeinhöcker geerdet, Wirbelsäule lang.","durationSec":8},{"pose":"twist","text":"Drehe dich aus der Taille, nicht aus dem Kiefer. Blick folgt zuletzt.","durationSec":16},{"pose":"sit","text":"Mitte, andere Seite, gleiche Dauer.","durationSec":8}]'::jsonb, 80, null, '{"kind":"daily","recommendedWeeks":4,"note":"Täglich je Seite ein Atemfenster von 20 Sekunden."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-box-breath', null, 'Boxatmung', 'Vier Seiten, ein klarer Rhythmus.', 'breath', array['cat-body', 'cat-breath', 'cat-mind', 'cat-pause']::text[], array['comp-stress', 'comp-focus']::text[], '[{"pose":"sit","text":"Sitz oder Stand. Schultern schwer.","durationSec":8},{"pose":"breathe","text":"4 Sekunden ein, 4 halten, 4 aus, 4 halten. Vier bis sechs Runden.","durationSec":32},{"pose":"sit","text":"Wieder normal atmen. Nichts muss sich großartig anfühlen.","durationSec":8}]'::jsonb, 120, null, '{"kind":"daily","recommendedWeeks":null,"note":"Immer, wenn Unruhe kommt – und einmal geplant am Tag, damit du es nicht vergisst."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-478', null, '4-7-8 Atmung', 'Ein längeres Ausatmen, das das Nervensystem bremst.', 'breath', array['cat-body', 'cat-breath', 'cat-evening']::text[], array['comp-sleep', 'comp-stress']::text[], '[{"pose":"lie","text":"Liegen oder sitzen. Zungenspitze darf hinter den Schneidezähnen ruhen.","durationSec":8},{"pose":"breathe","text":"Einatmen 4, halten 7, ausatmen 8. Vier Runden reichen.","durationSec":40},{"pose":"lie","text":"Danach nichts weiter tun. Einfach liegen bleiben.","durationSec":8}]'::jsonb, 100, null, '{"kind":"daily","recommendedWeeks":null,"note":"Abends im Bett oder davor. Dauerhaft im Plan lassen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-coherent', null, 'Kohärentes Atmen', 'Etwa sechs Atemzüge pro Minute, ohne Technik-Theater.', 'breath', array['cat-body', 'cat-breath', 'cat-mindfulness']::text[], array['comp-stress', 'comp-focus']::text[], '[{"pose":"sit","text":"Bequem sitzen. Eine Hand am Bauch, wenn es hilft.","durationSec":8},{"pose":"breathe","text":"5 Sekunden ein, 5 Sekunden aus. Weich, durch die Nase, wenn möglich.","durationSec":40},{"pose":"sit","text":"Öffne die Augen, wenn sie zu waren, und nimm den Raum wieder wahr.","durationSec":8}]'::jsonb, 180, null, '{"kind":"daily","recommendedWeeks":8,"note":"Drei Minuten täglich für acht Wochen, danach nach Bedarf."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-mantra-here', null, 'Mantra: Ich bin hier', 'Ein Satz, der dich aus dem Vorher und Nachher holt.', 'mantra', array['cat-mind', 'cat-mantras', 'cat-mindfulness', 'cat-pause']::text[], array['comp-focus', 'comp-stress']::text[], '[{"pose":"heart","text":"Hand aufs Brustbein. Einatmen.","durationSec":8},{"pose":"heart","text":"Leise oder innerlich: „Ich bin hier.“ Ausatmen: „Genau jetzt.“","durationSec":20},{"pose":"stand","text":"Augen auf. Einen Gegenstand im Raum benennen.","durationSec":8}]'::jsonb, 60, null, '{"kind":"daily","recommendedWeeks":null,"note":"Morgens einmal bewusst, und jederzeit, wenn du merkst, dass du nur noch im Kopf bist."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-mantra-fit', null, 'Mantra: I am fit', 'Nicht als Behauptung über den Körper, sondern als Richtung.', 'mantra', array['cat-mind', 'cat-mantras', 'cat-morning']::text[], array['comp-focus']::text[], '[{"pose":"stand","text":"Zwei Fußsohlen auf dem Boden. Aufrecht, nicht militärisch.","durationSec":8},{"pose":"heart","text":"Sag langsam: „I am fit.“ Fit im Sinn von: ich bleibe in Verbindung mit dem, was mir guttut.","durationSec":24},{"pose":"reachUp","text":"Einmal strecken, als würdest du den Satz in den Tag heben.","durationSec":8},{"pose":"stand","text":"Fertig. Kein Extra-Beweis nötig.","durationSec":8}]'::jsonb, 75, null, '{"kind":"daily","recommendedWeeks":null,"note":"Täglich am Morgen, bevor das Handy die Stimmung setzt."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-gratitude', null, 'Drei Dankbarkeiten', 'Drei konkrete Dinge, nicht drei Slogans.', 'mind', array['cat-mind', 'cat-mindfulness', 'cat-evening']::text[], array['comp-sleep', 'comp-stress']::text[], '[{"pose":"sit","text":"Setz dich oder lieg. Kein Journal nötig, Stimme reicht.","durationSec":8},{"pose":"heart","text":"Nenne drei Dinge von heute. So konkret wie „das warme Wasser“ statt „mein Leben“.","durationSec":30},{"pose":"sit","text":"Einen Atemzug länger bleiben als du willst, dann aufhören.","durationSec":8}]'::jsonb, 90, null, '{"kind":"daily","recommendedWeeks":null,"note":"Abends. Immer. Es ist kurz genug, dass Vergessen die einzige Hürde ist."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-body-scan', null, 'Mini-Bodyscan', 'Vom Fuß bis zum Kiefer, ohne etwas zu reparieren.', 'mind', array['cat-mind', 'cat-meditation', 'cat-evening']::text[], array['comp-sleep', 'comp-stress']::text[], '[{"pose":"lie","text":"Liegen, Arme neben dem Körper, Füße fallen lassen.","durationSec":8},{"pose":"breathe","text":"Wandere mit der Aufmerksamkeit: Füße, Knie, Becken, Rücken, Schultern, Kiefer.","durationSec":40},{"pose":"lie","text":"Wenn Gedanken kommen, zurück zum nächsten Körperteil. Fertig ist, wenn du bei den Augenlidern bist.","durationSec":8}]'::jsonb, 180, null, '{"kind":"daily","recommendedWeeks":4,"note":"Vier Wochen abends. Danach mindestens an unruhigen Tagen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-54321', null, '5-4-3-2-1 Anker', 'Fünf Dinge sehen, vier berühren, drei hören, zwei riechen, eins schmecken.', 'mind', array['cat-mind', 'cat-mindfulness', 'cat-pause']::text[], array['comp-stress', 'comp-focus']::text[], '[{"pose":"stand","text":"Bleib, wo du bist. Kein Extra-Ort.","durationSec":8},{"pose":"heart","text":"5 Dinge, die du siehst. 4, die du fühlst. 3 Geräusche. 2 Gerüche. 1 Geschmack.","durationSec":30},{"pose":"stand","text":"Ein normaler Atemzug. Weiter mit dem, was als Nächstes da ist.","durationSec":8}]'::jsonb, 90, null, '{"kind":"every_n_days","everyNDays":1,"recommendedWeeks":null,"note":"Nicht starr planen: aufheben für Momente, in denen es kippt – und einmal pro Woche üben, damit der Weg bekannt ist."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-morning-reach', null, 'Morgenstrecken im Stand', 'Drei Atemzüge Länge, bevor der Tag dich übernimmt.', 'movement', array['cat-body', 'cat-morning', 'cat-mobility', 'cat-daily']::text[], array['comp-back', 'comp-shoulders']::text[], '[{"pose":"stand","text":"Noch im Schlafanzug ist erlaubt.","durationSec":8},{"pose":"reachUp","text":"Arme heben, seitlich lang werden, in die Fersen sinken.","durationSec":16},{"pose":"fold","text":"Einmal schwer hängen lassen.","durationSec":8},{"pose":"stand","text":"Aufrichten. Tag darf beginnen.","durationSec":8}]'::jsonb, 60, null, '{"kind":"daily","recommendedWeeks":null,"note":"Jeden Morgen, noch bevor Mails. Immer behalten."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-desk-break', null, 'Zwei-Minuten-Bildschirmpause', 'Nacken, Schultern, Atem – das, was du zwischen zwei Tasks vergisst.', 'movement', array['cat-daily', 'cat-pause', 'cat-neck', 'cat-shoulders']::text[], array['comp-neck', 'comp-shoulders', 'comp-focus']::text[], '[{"pose":"stand","text":"Steh auf. Ja, wirklich aufstehen.","durationSec":8},{"pose":"neckTilt","text":"Nacken neigen, beide Seiten.","durationSec":12},{"pose":"chestOpen","text":"Schultern kreisen und die Brust öffnen.","durationSec":10},{"pose":"breathe","text":"Vier ruhige Atemzüge.","durationSec":16}]'::jsonb, 120, null, '{"kind":"weekdays","recommendedWeeks":null,"note":"An Arbeitstagen, idealerweise zweimal. Der Plan erinnert dich an eine Runde; die zweite ist Bonus."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-jaw-release', null, 'Kiefer locker lassen', 'Zunge, Zähne und Schläfen erinnern, dass sie nicht arbeiten müssen.', 'movement', array['cat-body', 'cat-neck', 'cat-pause', 'cat-daily']::text[], array['comp-neck', 'comp-stress']::text[], '[{"pose":"sit","text":"Lippen geschlossen, Zähne nicht. Zunge hinter den Schneidezähnen ablegen.","durationSec":8},{"pose":"neckTilt","text":"Kiefer ganz leicht nach links und rechts gleiten lassen. Kein Dehnen, nur Loslassen.","durationSec":16},{"pose":"sit","text":"Ein Atemzug in die Schläfen. Schultern dürfen mitfallen.","durationSec":8}]'::jsonb, 70, null, '{"kind":"weekdays","recommendedWeeks":null,"note":"An Arbeitstagen, sobald du merkst, dass die Zähne aufeinanderliegen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-wrist-circles', null, 'Handgelenke kreisen', 'Zwei Kreise gegen das starre Tippen.', 'movement', array['cat-daily', 'cat-pause', 'cat-mobility']::text[], array['comp-shoulders', 'comp-focus']::text[], '[{"pose":"stand","text":"Arme vor dem Körper, Finger locker.","durationSec":8},{"pose":"chestOpen","text":"Handgelenke langsam kreisen, dann die andere Richtung. Atme dabei normal.","durationSec":20},{"pose":"stand","text":"Hände ausschütteln, als wären sie nass.","durationSec":8}]'::jsonb, 60, null, '{"kind":"weekdays","recommendedWeeks":null,"note":"Unter der Woche zwischen zwei Schreibblöcken. Kurz genug, um es wirklich zu tun."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-eye-rest', null, 'Blick in die Ferne', 'Zwanzig Sekunden weit schauen, damit die Augen nicht nur den Bildschirm kennen.', 'mind', array['cat-daily', 'cat-pause', 'cat-mindfulness']::text[], array['comp-focus', 'comp-stress']::text[], '[{"pose":"sit","text":"Vom Schirm wegdrehen. Schultern schwer.","durationSec":8},{"pose":"breathe","text":"Einen Punkt in der Ferne wählen und 20 ruhige Sekunden dort bleiben.","durationSec":20},{"pose":"sit","text":"Blinzeln. Danach darf der Bildschirm wieder da sein.","durationSec":8}]'::jsonb, 50, null, '{"kind":"weekdays","recommendedWeeks":null,"note":"An Bildschirmtagen oft. Der Plan erinnert an eine Runde; weitere sind freiwillig."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-pelvic-tilt', null, 'Beckenkippen im Liegen', 'Kleine Bewegung für den unteren Rücken, ohne ihn zu verbiegen.', 'movement', array['cat-body', 'cat-back', 'cat-hips', 'cat-evening']::text[], array['comp-back', 'comp-hips']::text[], '[{"pose":"lie","text":"Rückenlage, Knie aufgestellt, Füße am Boden.","durationSec":8},{"pose":"cat","text":"Becken kippen: Lendenwirbel kurz zum Boden, dann die natürliche Kurve wieder erlauben.","durationSec":24},{"pose":"lie","text":"Still liegen und den Kontakt zum Boden spüren.","durationSec":8}]'::jsonb, 90, null, '{"kind":"daily","recommendedWeeks":4,"note":"Vier Wochen abends, danach an Tagen mit viel Sitzen behalten."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-calf-stretch', null, 'Waden an der Wand', 'Eine Seite nach der anderen lang machen, ohne zu federn.', 'movement', array['cat-body', 'cat-knees', 'cat-mobility', 'cat-daily']::text[], array['comp-knees', 'comp-hips']::text[], '[{"pose":"stand","text":"Hände an die Wand, ein Fuß weit hinten, hintere Ferse bleibt am Boden.","durationSec":8},{"pose":"lunge","text":"Vorderes Knie beugen, hinteres Bein lang. 20 Sekunden, dann Seite wechseln.","durationSec":20},{"pose":"stand","text":"Ausschütteln. Waden dürfen warm sein, nicht brennen.","durationSec":8}]'::jsonb, 80, null, '{"kind":"days","daysOfWeek":[1,3,5],"timesPerWeek":3,"recommendedWeeks":4,"note":"Drei Mal pro Woche, besonders nach langem Stehen oder Gehen in starren Schuhen."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-shoulder-dump', null, 'Schultern abladen', 'Ein Abendritual: hochziehen, fallen lassen, fertig.', 'movement', array['cat-daily', 'cat-evening', 'cat-shoulders']::text[], array['comp-shoulders', 'comp-stress', 'comp-sleep']::text[], '[{"pose":"stand","text":"Stehen oder sitzen. Einatmen, Schultern zu den Ohren.","durationSec":8},{"pose":"chestOpen","text":"Ausatmen und die Schultern fallen lassen, schwerer als du denkst. Drei Runden.","durationSec":16},{"pose":"sit","text":"Arme hängen. Nichts weiter aufrichten.","durationSec":8}]'::jsonb, 70, null, '{"kind":"daily","recommendedWeeks":null,"note":"Abends, wenn der Tag noch in den Schultern hängt. Dauerhaft sinnvoll."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z'),
('ex-walk-attention', null, 'Zwei Minuten gehen', 'Nur gehen und merken, dass die Füße den Boden treffen.', 'mind', array['cat-daily', 'cat-mindfulness', 'cat-pause']::text[], array['comp-focus', 'comp-stress']::text[], '[{"pose":"stand","text":"Aufstehen. Kein Ziel, nur ein paar Meter.","durationSec":8},{"pose":"tree","text":"Langsam gehen. Bei jedem Schritt: Ferse, Fußballen, Zehen.","durationSec":40},{"pose":"stand","text":"Stehen bleiben. Einen Atemzug, dann zurück zu dem, was als Nächstes da ist.","durationSec":8}]'::jsonb, 120, null, '{"kind":"every_n_days","everyNDays":2,"recommendedWeeks":null,"note":"Alle zwei Tage, oder immer wenn der Kopf zu voll ist. Kein Trainingsspaziergang."}'::jsonb, '{"type":"catalog"}'::jsonb, true, '2026-01-01T09:00:00.000Z', '2026-01-01T09:00:00.000Z')
on conflict (id) do update set
  title = excluded.title,
  summary = excluded.summary,
  kind = excluded.kind,
  category_ids = excluded.category_ids,
  complaint_ids = excluded.complaint_ids,
  steps = excluded.steps,
  default_duration_sec = excluded.default_duration_sec,
  default_reps = excluded.default_reps,
  suggested_rhythm = excluded.suggested_rhythm,
  source = excluded.source,
  is_system = excluded.is_system,
  updated_at = excluded.updated_at;
